### 
POST http://localhost:3000/supplier
Content-Type: application/json

{
    "nombreProveedor": "Supplier_3",
    "tipoDeProducto": "Supplier_description_3",
    "logo": "logo_link"
    
}

### 
PUT  http://localhost:3000/supplier
Content-Type: application/json

{
    "id":14,
    "nombreProveedor": "Supplier_3",
    "tipoDeProducto": "Supplier_description_3",
    "logo": "logo_link"
}

### 
GET  http://localhost:3000/supplier/16
